clone:
  CLONE REPO:
    image: plugins/git
    depth: 1

pipeline:
  INSTALL DEPENDENCIES:
    image: node:8.10
    commands:
      - npm install

  LINT:
    image: node:8.10
    commands:
      - npm run lint

  UNIT TEST:
    image: node:8.10
    commands:
      - npm run test

  BUILD:
    image: node:8.10
    commands:
      - npm run build

  PUBLISH:
    image: node:8.10
    commands:
      - ID_RSA=$GITHUB_SSH_KEY
      - export ID_RSA
      - sh ./scripts/github-access.sh
      - sh ./scripts/npm-token.sh $NPM_TOKEN
      - sh ./scripts/publish.sh $DRONE_COMMIT_MESSAGE
    secrets: [ github_ssh_key, npm_token ]
    when:
      branch: [ master ]
      event: [ push ]

  NOTIFY PULL REQUEST TO TEAMS:
    group: notification
    image: globx/drone-plugin-teams:linux-amd64-build-1
    secrets: [ teams_webhook ]
    message_title: >
      [ ${DRONE_REPO_NAME} ]
    message_success: >
      ${DRONE_BRANCH} Sandbox: has been updated
    message_failure: >
      ${DRONE_BRANCH} Sandbox: has failed to update
    link_text: "Pull Request"
    link_url: "https://github.com/${DRONE_REPO}/pull/${DRONE_PULL_REQUEST}"
    when:
      status: [ success, failure ]
      event: [ pull_request ]
