clone:
  CLONE REPO:
    image: plugins/git
    depth: 1

pipeline:
  INSTALL DEPENDENCIES:
    image: node:8.10
    commands:
      - npm install

  LINT:
    image: node:8.10
    commands:
      - npm run lint

  UNIT TEST:
    image: node:8.10
    commands:
      - npm run test

  BUILD:
    image: node:8.10
    commands:
      - npm run build

  PUBLISH:
    image: node:8.10
    commands:
      - sh ./scripts/publish.sh $DRONE_COMMIT_MESSAGE

    when:
      branch: [ master ]
      event: [ push ]

